{ pkgs
, lib
, config
, flake
, ...
}:
let
  # Build the plugin from the flake-locked source against the exact Hyprland
  # package Home Manager resolves for this configuration. ABI between the
  # plugin and compositor is unstable, so both must come from the same build.
  hypr-autoscroll = pkgs.callPackage ../../packages/hypr-autoscroll.nix {
    src = flake.inputs.hypr-autoscroll;
    hyprland = config.wayland.windowManager.hyprland.finalPackage;
  };
in
{
  config = lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = true;
      configType = "lua";

      # Declarative plugin load. Home Manager resolves this package at
      # `${package}/lib/lib${pname}.so`.
      plugins = [ hypr-autoscroll ];

      settings.config = {
        autogenerated = false;
        input = {
          numlock_by_default = true;
          touchpad.natural_scroll = true;
        };
      };

      extraConfig = ''
        local function described(description)
          return { description = description }
        end

        hl.on("hyprland.start", function()
          if hl.plugin.hypr_autoscroll then
            hl.plugin.hypr_autoscroll.middle_mode("off")
          end
        end)

        hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"), described("Applications: Open terminal"))
        hl.bind("SUPER + Q", hl.dsp.window.close(), described("Windows: Close active window"))

        hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }), described("Windows: Focus left"))
        hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }), described("Windows: Focus right"))
        hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }), described("Windows: Focus up"))
        hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }), described("Windows: Focus down"))

        hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }), described("Workspaces: Switch to workspace 1"))
        hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }), described("Workspaces: Switch to workspace 2"))
        hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }), described("Workspaces: Switch to workspace 3"))
        hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }), described("Workspaces: Switch to workspace 4"))
        hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }), described("Workspaces: Switch to workspace 5"))

        hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }), described("Workspaces: Move window to workspace 1"))
        hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }), described("Workspaces: Move window to workspace 2"))
        hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }), described("Workspaces: Move window to workspace 3"))
        hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }), described("Workspaces: Move window to workspace 4"))
        hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }), described("Workspaces: Move window to workspace 5"))

        hl.bind("SUPER + Space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), described("Shell: Toggle application launcher"))
        hl.bind("SUPER + S", hl.dsp.exec_cmd("dms ipc call settings toggle"), described("Shell: Toggle settings"))
        hl.bind("SUPER + C", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), described("Shell: Toggle clipboard history"))
        hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"), described("Shell: Choose wallpaper"))
        hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), described("Shell: Toggle power menu"))
        hl.bind("SUPER + A", hl.dsp.exec_cmd("dms ipc call widget toggle sathiAi"), described("Shell: Toggle AI chat"))
        hl.bind("SUPER + N", hl.dsp.exec_cmd("dms ipc call control-center toggle"), described("Shell: Toggle control center"))
        hl.bind("SUPER + M", hl.dsp.exec_cmd("dms ipc call dash toggle media"), described("Shell: Toggle media dashboard"))
        hl.bind("SUPER + P", hl.dsp.exec_cmd("dms ipc call processlist toggle"), described("Shell: Toggle process list"))
        hl.bind("SUPER + Tab", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), described("Shell: Toggle workspace overview"))
        hl.bind("SUPER + Slash", hl.dsp.exec_cmd("dms ipc call hypr toggleBinds"), described("Shell: Toggle keybind cheatsheet"))
        hl.bind("SUPER + D", hl.dsp.exec_cmd("dms ipc call settings open"), described("Utilities: Configure displays"))

        hl.bind("SUPER + CTRL + A", function()
          if hl.plugin.hypr_autoscroll then
            hl.plugin.hypr_autoscroll.middle_mode("toggle")
          end
        end, described("Utilities: Toggle middle-button autoscroll"))

        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), { locked = true, repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), { locked = true, repeating = true })

        hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
        hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })
        hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
        hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })
        hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })

        require("dms.colors")
        require("dms.outputs")
        require("dms.layout")
        require("dms.cursor")
        require("dms.binds-user")
        require("dms.windowrules")
      '';
    };
  };
}
