{ pkgs
, lib
, ...
}:
{
  # Hyprland Home Manager compositor config (SHOA-1037, reverting the niri swap
  # SHOA-997). Restored from the pre-niri Hyprland setup (git ad2aea6,
  # modules/home/hyprland.nix) with three deliberate reconciliations so it works
  # with the kept Noctalia shell instead of the removed DankMaterialShell:
  #
  #   1. Shell IPC binds are remapped from the removed DMS `dms ipc call …`
  #      shims to the Noctalia V5 CLI (`noctalia msg <verb>`). The verb mapping
  #      is the one validated during the niri migration (SHOA-1007) against
  #      noctalia-shell v5.0.0-beta.9 — see the per-bind comments below.
  #   2. The `require("dms.*")` lua seeding block at the end of the old config
  #      is dropped: those includes (colors/outputs/layout/cursor/binds/
  #      windowrules) were injected by DMS's Hyprland home module, which no
  #      longer exists. Noctalia is a Quickshell/QML shell and does not inject
  #      Hyprland lua config; theming is owned by programs.noctalia
  #      (modules/home/noctalia.nix) and cursor by home.pointerCursor below.
  #   3. The hypr-autoscroll plugin (and its SUPER+CTRL+A middle-mode toggle)
  #      is NOT restored: the founder explicitly requested dropping it during
  #      the Hyprland→niri swap (SHOA-997, "drop the hypr-autoscroll Hyprland
  #      plugin"), so that removal decision stands here.
  #
  # Idle/DPMS is owned by stasis (modules/home/idle.nix); locking is Noctalia's
  # shell-native lock screen (SHOA-1040, replacing hypridle + the legacy Wayland locker
  # SHOA-993/1037). The SUPER+L bind below runs `noctalia msg session lock`
  # directly: stasis does not lock on `loginctl lock-session` (it only tracks
  # LockedHint), so the bind spawns the locker like the idle/pre-sleep steps do.
  config = lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
    home.pointerCursor = {
      enable = true;
      package = pkgs.adwaita-icon-theme;
      name = "Adwaita";
      size = 24;
    };

    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = true;
      configType = "lua";

      settings.config = {
        autogenerated = false;
        input = {
          numlock_by_default = true;
          touchpad.natural_scroll = true;
        };
        misc = {
          background_color = "rgb(000000)";
          disable_hyprland_logo = true;
          disable_splash_rendering = true;
          force_default_wallpaper = 0;
        };
      };

      # Explicit monitor rule pinning scale to 1.0 (SHOA-1050). Hyprland
      # auto-scales unconfigured monitors from EDID PPI (getDefaultScale:
      # PPI > 200 -> 2.0, PPI > 140 -> 1.5, else 1.0); niri defaults every
      # output to 1.0, so without this the post-swap UI renders oversized.
      settings.monitor = [
        {
          output = "";
          mode = "preferred";
          position = "auto";
          scale = 1;
        }
      ];

      extraConfig = ''
        local function described(description)
          return { description = description }
        end

        -- Terminal: kitty (the shared workstation terminal since SHOA-991;
        -- replaces the pre-niri `foot` bind, which is no longer installed).
        hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), described("Applications: Open terminal"))
        hl.bind("SUPER + Q", hl.dsp.window.close(), described("Windows: Close active window"))
        hl.bind("SUPER + L", hl.dsp.exec_cmd("noctalia msg session lock"), described("Session: Lock screen"))

        hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }), described("Windows: Focus left"))
        hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }), described("Windows: Focus right"))
        hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }), described("Windows: Focus up"))
        hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }), described("Windows: Focus down"))

        hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }), described("Workspaces: Switch to workspace 1"))
        hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }), described("Workspaces: Switch to workspace 2"))
        hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }), described("Workspaces: Switch to workspace 3"))
        hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }), described("Workspaces: Switch to workspace 4"))
        hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }), described("Workspaces: Switch to workspace 5"))

        hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }), described("Workspaces: Move window to workspace 1"))
        hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }), described("Workspaces: Move window to workspace 2"))
        hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }), described("Workspaces: Move window to workspace 3"))
        hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }), described("Workspaces: Move window to workspace 4"))
        hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }), described("Workspaces: Move window to workspace 5"))

        -- Shell (Noctalia V5) — remapped from the removed DMS `dms ipc call …`
        -- binds to `noctalia msg <verb>` (SHOA-1007 mapping; panel ids: launcher,
        -- clipboard, wallpaper, session, control-center). `noctalia` is placed on
        -- $PATH by programs.noctalia (modules/home/noctalia.nix).
        hl.bind("SUPER + Space", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"), described("Shell: Toggle application launcher"))
        hl.bind("SUPER + S", hl.dsp.exec_cmd("noctalia msg settings-toggle"), described("Shell: Toggle settings"))
        hl.bind("SUPER + C", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"), described("Shell: Toggle clipboard history"))
        hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"), described("Shell: Choose wallpaper"))
        hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("noctalia msg panel-toggle session"), described("Shell: Toggle session menu"))
        hl.bind("SUPER + N", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"), described("Shell: Toggle control center"))
        hl.bind("SUPER + D", hl.dsp.exec_cmd("noctalia msg settings-toggle"), described("Utilities: Toggle settings (display config)"))

        -- The pre-niri Hyprland keymap also bound SUPER+A (dms sathiAi / AI chat),
        -- SUPER+M (dms media dashboard), SUPER+P (dms processlist), SUPER+Tab
        -- (dms hypr toggleOverview) and SUPER+/ (dms hypr toggleBinds). Those
        -- called DankMaterialShell surfaces that Noctalia V5 has no equivalent
        -- for; the accepted DMS→Noctalia migration (SHOA-1004/1007/1008) dropped
        -- exactly these, so they are intentionally left unbound here rather than
        -- pointed at a dead verb. If Noctalia later exposes these surfaces they
        -- can be re-bound in a follow-up.

        -- Media / brightness keys (usable while locked). Remapped to
        -- `noctalia msg` (SHOA-1007). Volume keeps the explicit 5-unit step;
        -- brightness omits the arg because Noctalia's first positional there is
        -- <target>, so its configured step applies.
        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("noctalia msg volume-up 5"), { locked = true, repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("noctalia msg volume-down 5"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("noctalia msg brightness-up"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia msg brightness-down"), { locked = true, repeating = true })

        hl.bind("XF86AudioMute", hl.dsp.exec_cmd("noctalia msg volume-mute"), { locked = true })
        hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("noctalia msg mic-mute"), { locked = true })
        hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("noctalia msg media toggle"), { locked = true })
        hl.bind("XF86AudioNext", hl.dsp.exec_cmd("noctalia msg media next"), { locked = true })
        hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("noctalia msg media previous"), { locked = true })
      '';
    };
  };
}
