"""Shared attribution-pattern detection for `block-attribution.sh` and
`scripts/check-agent-policy.py`'s `--commits` mode.

One set of regexes, read by the PreToolUse hook (a commit or PR the session is
about to create) and by the CI backstop (a commit that reached `main` without
going through a hook at all -- a human push, or a tool that does not run
hooks). Denied:

- a `Co-Authored-By` / `Co-authored-by` / `Signed-off-by` / `Generated-by` /
  `Assisted-by` trailer (any case) whose value names Claude, Anthropic, an
  `@anthropic.com` address, or a ShockStruck agent identity (`<words> Lead`,
  `<words> Junior`, `Research`, `Resolver`)
- a `Claude-Session` trailer (any case) -- denied on the key alone, since its
  value is a claude.ai session URL and never names Claude by word
- a line containing `Generated with Claude Code`, `Generated with
  [Claude Code]`, `Generated by Claude`, or `🤖 Generated`
- an `@anthropic.com` address anywhere
- an address at the committing identity's own domain anywhere (the "owner
  domain"), or at a domain `policy.json`'s optional `attribution.blockedEmails`
  names

Deliberately not a bare `Claude` / `Anthropic` word match: this repository
legitimately commits messages about `.claude/` and `CLAUDE.md`, so the name
check only runs on a trailer's value, never on the message as a whole.
"""

from __future__ import annotations

import re

TRAILER_KEYS = (
    "Co-Authored-By",
    "Signed-off-by",
    "Generated-by",
    "Assisted-by",
)
# Checked on the key alone -- its value is a claude.ai session URL, which
# never names Claude, Anthropic or an agent identity by word.
KEY_ONLY_TRAILER_KEYS = ("Claude-Session",)
# Not line-anchored: a trailer can be its own physical line in a heredoc
# commit body, or a whole `-m "Co-Authored-By: ..."` argument sitting mid-line
# next to other `-m`/`-F` flags. The value stops at the next quote, backslash
# or newline, so it never swallows the shell syntax that follows it.
TRAILER_RE = re.compile(
    r"\b(?P<key>"
    + "|".join(re.escape(key) for key in (*TRAILER_KEYS, *KEY_ONLY_TRAILER_KEYS))
    + r")\s*:\s*(?P<value>[^\n\"'\\]*)",
    re.IGNORECASE,
)
KEY_ONLY_TRAILER_KEYS_LOWER = frozenset(key.lower() for key in KEY_ONLY_TRAILER_KEYS)
CLAUDE_NAME_RE = re.compile(r"\bClaude(?:\s+Code)?\b|\bAnthropic\b", re.IGNORECASE)
AGENT_IDENTITY_RE = re.compile(
    r"\b[A-Z][\w.'-]*(?:\s+[A-Z][\w.'-]*)*\s+(?:Lead|Junior)\b|\bResearch\b|\bResolver\b"
)
ANTHROPIC_EMAIL_RE = re.compile(r"[\w.+-]+@anthropic\.com", re.IGNORECASE)
GENERATED_LINE_RE = re.compile(
    r"Generated with \[?Claude Code\]?|Generated by Claude|\U0001F916\s*Generated",
    re.IGNORECASE,
)


def owner_email_pattern(domain: str) -> re.Pattern[str]:
    """Pattern matching any address at `domain`."""
    return re.compile(rf"[\w.+-]+@{re.escape(domain)}\b", re.IGNORECASE)


def blocked_email_pattern(addresses: tuple[str, ...]) -> re.Pattern[str] | None:
    if not addresses:
        return None
    return re.compile("|".join(re.escape(address) for address in addresses), re.IGNORECASE)


def trailer_match(text: str) -> re.Match[str] | None:
    """The first trailer in `text` naming Claude, Anthropic or a ShockStruck
    agent identity, or a key-only trailer such as `Claude-Session`, or None.
    The bare-word check is confined to a value here, so it never fires on
    ordinary prose about `.claude/` or `CLAUDE.md`."""
    for match in TRAILER_RE.finditer(text):
        if match.group("key").lower() in KEY_ONLY_TRAILER_KEYS_LOWER:
            return match
        value = match.group("value")
        if (
            CLAUDE_NAME_RE.search(value)
            or ANTHROPIC_EMAIL_RE.search(value)
            or AGENT_IDENTITY_RE.search(value)
        ):
            return match
    return None


def find_violation(
    text: str,
    owner_pattern: re.Pattern[str] | None = None,
    blocked_pattern: re.Pattern[str] | None = None,
) -> str | None:
    """The first offending snippet in `text`, quoted for a denial reason, or
    None. Checked in this order: an attribution trailer, a "Generated with
    Claude Code"-shaped line, an `@anthropic.com` address, an address at the
    committing identity's own domain, an address `policy.json` names."""
    match = trailer_match(text)
    if match is not None:
        return match.group(0).strip()
    match = GENERATED_LINE_RE.search(text)
    if match is not None:
        return match.group(0).strip()
    match = ANTHROPIC_EMAIL_RE.search(text)
    if match is not None:
        return match.group(0).strip()
    if owner_pattern is not None:
        match = owner_pattern.search(text)
        if match is not None:
            return match.group(0).strip()
    if blocked_pattern is not None:
        match = blocked_pattern.search(text)
        if match is not None:
            return match.group(0).strip()
    return None
