# Proton-CachyOS — CachyOS's Proton fork (FSR 4/OptiScaler auto-injection,
# a newer Wine base). Not in nixpkgs (no `proton-cachyos` attribute exists
# upstream); CachyOS does build it from source, but only publishes prebuilt
# release tarballs, so this package consumes those binaries rather than
# building from the source repository.
#
# Nix-built rather than the ProtonUp-Qt route already on the console
# (`modules/nixos/console/launchers.nix`): ProtonUp-Qt drops the tool into
# the user's mutable `~/.local/share/Steam/compatibilitytools.d/`, which
# only Steam and manual per-game pickers see. A store path, by contrast, can
# be set once as `environment.sessionVariables.PROTONPATH`
# (`console/launchers.nix`) and becomes the default Proton for every
# umu-launcher invocation — including OpenGameInstaller's, which spawns
# `umu-run` with a spread of `process.env` and only overrides `PROTONPATH`
# per-game when a game has its own `protonVersion` set
# (`application/src/electron/handlers/helpers.app/umu-environment.ts`,
# upstream Nat3z/OpenGameInstaller). That is what makes the umu default
# declarative instead of a manual ProtonUp-Qt install repeated after every
# reinstall.
#
# `x86_64_v3`: the console is the desktop's Zen 4 class, which is
# v3-capable, and ProtonUp-Qt's own Proton-CachyOS installer
# (`pupgui2/resources/ctmods/ctmod_protoncachyos.py`) picks the same
# `x86_64_v3` asset whenever the host's hwcaps allow it. Fall back to the
# plain `x86_64` release asset (drop `_v3` from `toolName` below) on
# non-v3-capable hardware.
#
# FSR4/OptiScaler never write into the tool directory: OptiScaler's upscaler
# downloads land in `$XDG_CACHE_HOME/protonfixes/upscalers`, and
# `PROTON_USE_OPTISCALER`/`PROTON_FSR4_UPGRADE` state lands in the Wine
# prefix's `drive_c/windows/system32/umu/` (`protonfixes/upscalers.py`,
# upstream Open-Wine-Components/umu-protonfixes). A read-only Nix store path
# for the tool itself is therefore fine, the same as nixpkgs' own
# `proton-ge-bin`.
#
# `dontConfigure`/`dontBuild`/`dontFixup`: fixup's binary stripping and
# shebang patching would corrupt the Wine binaries and the scripts meant to
# run inside umu/Steam's pressure-vessel container, not on the host.
# nixpkgs' own `proton-ge-bin` avoids the same problem differently — it
# symlinks into the extracted release tree rather than copying, so fixup has
# nothing of its own to touch; `dontFixup` is this package's equivalent for a
# real copy.
#
# Declarative per-game defaults via `user_settings.py`: Proton's own `proton`
# script loads a `user_settings.py` from its tool directory at launch
# (`init_session`: `self.user_settings_file = self.path("user_settings.py")`,
# then `import user_settings` and `for key, value in
# user_settings.user_settings.items(): if key not in self.env: self.env[key]
# = value`, ValveSoftware/Proton, carried into proton-cachyos unchanged).
# Because every launcher — umu, Steam, and therefore Heroic/Lutris/OGI, which
# all delegate to umu or Steam — execs `<tool>/proton` directly, a
# `user_settings.py` dropped into `$steamcompattool` applies to every game
# run through this tool, while any variable a game's own launch environment
# already sets (Steam launch options, OGI's Game Arguments, etc.) takes
# precedence, since the loader only fills in variables that are not already
# set. `userSettings` below (an attrset of string to string) becomes that
# file's `user_settings` dict; leave it `{ }` for no tool-level defaults.
#
# Pin/update path:
#   1. Find the newest `cachyos-*-slr` tag:
#        curl -s https://api.github.com/repos/CachyOS/proton-cachyos/releases/latest | jq -r .tag_name
#   2. Bump `version` below to the tag with the leading `cachyos-` and
#      trailing `-slr` stripped.
#   3. Take the hex digest from that release's `.sha512sum` asset and
#      convert it to SRI:
#        python3 -c 'import base64,sys;print("sha512-"+base64.b64encode(bytes.fromhex(sys.argv[1])).decode())' <hex>
{ lib
, stdenvNoCC
, fetchurl
, writeText
, userSettings ? { }
}:
let
  pname = "proton-cachyos-bin";
  version = "11.0-20260703";
  toolName = "proton-cachyos-${version}-slr-x86_64_v3";

  src = fetchurl {
    url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-${version}-slr/${toolName}.tar.xz";
    hash = "sha512-WRGoYLDdESaPNzbTMoenSZOt2pjkyURNFc+fiYj86pwdk6AeFNEBkCFFit0XVQlev2wqglyg1JzjSbNbF5zQEw==";
  };

  # Generated by this package from `userSettings`; see the header comment for
  # the mechanism. A JSON object of strings is also a valid Python dict
  # literal, so `builtins.toJSON` is enough to produce `user_settings.py`'s
  # one required assignment. Values must be strings (Proton's loader reads
  # them as environment-variable text); per-game settings always win, since
  # `proton` only fills in a variable that is not already set.
  userSettingsFile = writeText "user_settings.py" ''
    # Generated by packages/proton-cachyos-bin.nix (userSettings argument).
    # Proton's `proton` script loads this file at launch and applies each
    # entry only when the variable is not already set in the launch
    # environment, so a game's own launch arguments always override these.
    # Values must be strings.
    user_settings = ${builtins.toJSON userSettings}
  '';
in
stdenvNoCC.mkDerivation {
  inherit pname version src;

  outputs = [ "out" "steamcompattool" ];

  dontConfigure = true;
  dontBuild = true;
  dontFixup = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/doc/${pname}
    echo "Proton-CachyOS ${version}, packaged in $steamcompattool" > $out/share/doc/${pname}/README

    mkdir -p $steamcompattool
    cp -a . $steamcompattool/
    ${lib.optionalString (userSettings != { }) "cp ${userSettingsFile} $steamcompattool/user_settings.py"}

    substituteInPlace $steamcompattool/compatibilitytool.vdf \
      --replace-fail "${toolName}" "Proton-CachyOS"

    runHook postInstall
  '';

  meta = {
    description = "CachyOS's Proton fork with FSR 4 / OptiScaler auto-injection support";
    homepage = "https://github.com/CachyOS/proton-cachyos";
    changelog = "https://github.com/CachyOS/proton-cachyos/releases/tag/cachyos-${version}-slr";
    license = lib.licenses.bsd3;
    platforms = [ "x86_64-linux" ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
