name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      OMNIX_FLAKE: github:juspay/omnix/ccda191140205c0cd1aa95bec4bb0726c0146496
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: nixbuild/nix-quick-install-action@1f095fee853b33114486cfdeae62fa099cda35a9 # v33
      - name: om show
        run: nix run "$OMNIX_FLAKE" -- show .
      - name: om ci
        run: nix run "$OMNIX_FLAKE" -- ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems x86_64-linux

      - name: Evaluate workstation configurations
        run: |
          nix eval .#nixosConfigurations.desktop.config.system.build.toplevel.drvPath
          nix eval .#nixosConfigurations.laptop.config.system.build.toplevel.drvPath

      - name: Build workstation configurations
        run: |
          nix build --no-link .#nixosConfigurations.desktop.config.system.build.toplevel
          nix build --no-link .#nixosConfigurations.laptop.config.system.build.toplevel
