name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [aarch64-darwin, x86_64-darwin, x86_64-linux]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: om show
        run: om show .
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}"

      - name: Evaluate workstation configurations
        if: matrix.system == 'x86_64-linux'
        run: |
          nix eval .#nixosConfigurations.desktop.config.system.build.toplevel.drvPath
          nix eval .#nixosConfigurations.laptop.config.system.build.toplevel.drvPath

      - name: Build workstation configurations
        if: matrix.system == 'x86_64-linux'
        run: |
          nix build --no-link .#nixosConfigurations.desktop.config.system.build.toplevel
          nix build --no-link .#nixosConfigurations.laptop.config.system.build.toplevel
